### ISSUE TITLE
Links to Models

### ISSUE THREAD

**Issue by zlapp** [robin-chan/meta-ood#1]
Hi, the links to the trained models are not valid.

Is it possible to reload them?

Thanks!

The given links are:
http://www-ai.math.uni-wuppertal.de/~chan/weights/DeepLabV3+_WideResNet38_epoch_4_alpha_0.9.pth
http://www-ai.math.uni-wuppertal.de/~chan/weights/DualGCNNet_res50_epoch_11_alpha_0.25.pth

**Comment by robin-chan** [comment]
I have updated the links in the README:

https://uni-wuppertal.sciebo.de/s/kCgnr0LQuTbrArA/download
https://uni-wuppertal.sciebo.de/s/VAXiKxZ21eAF68q/download
