### ISSUE TITLE
About OOD data used during training

### ISSUE THREAD

**Issue by haoz19** [robin-chan/meta-ood#4]
Hello Robin,

Thanks for your great work, which inspired me a lot.

I saw that many works followed your way to extract OOD samples from external datasets such as CoCo. I saw your code and you separated all classes of coco into two classes: not anomaly (19 classes same with cityscapes) and anomaly (all other classes), and you did not abandon the classes, which is included in the test anomaly dataset sets, e.g. animals and airplanes  (some test set is not even public, so I don't think you can know what is in the test set).  Am I understanding right?

Best Wishes,
Hao

**Comment by robin-chan** [comment]
Hello Hao,

yes, you are right. When choosing a real-world OoD proxy, it is nearly impossible to make sure that the objects in the OoD samples never occur in other test datasets. We tried our best in [this work](https://arxiv.org/pdf/2012.06575.pdf) by excluding all images with objects also appearing in the LostAndFound test dataset, which we knew beforehand we will evaluate on.

However, when using the same model for e.g. the [SegmentMeIfYouCan Anomaly Track (Tab. 15)](https://arxiv.org/pdf/2104.14812.pdf), we observe that the anomaly scores are biased towards animals, which appear more frequently in COCO. Therefore, the challenge still remains to find an unbiased but representative OoD proxy with respect to all possible OoD objects. Looking at the [SegmentMeIfYouCan leaderboard ](https://segmentmeifyoucan.com/leaderboard), synthetic OoD samples seem promising.

Best,
Robin.

**Comment by haoz19** [comment]
Thanks for your answers!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Robin Chan ***@***.***>
发送时间: Thursday, February 16, 2023 1:17:01 PM
收件人: robin-chan/meta-ood ***@***.***>
抄送: Zhang, Hao ***@***.***>; Author ***@***.***>
主题: Re: [robin-chan/meta-ood] About OOD data used during training (Issue #4)


Closed #4<https://urldefense.com/v3/__https://github.com/robin-chan/meta-ood/issues/4__;!!DZ3fjg!7XQedDFOEHYO9BANpavnXPTlBTwbykfdHdE0NtsJnfx-W0px3Yb5Y-BJUkWoLVEuaPKL3wVGI6qEj5hwShefrdPoszDk$> as completed.

―
