### ISSUE TITLE
Download Checkpoint

### ISSUE THREAD

**Issue by 343gltysprk** [robin-chan/meta-ood#6]
Hi Robin,
The pre-trained model is no longer available at https://uni-wuppertal.sciebo.de/s/kCgnr0LQuTbrArA/download
Can you share a new link?
Thank you

**Comment by robin-chan** [comment]
Hi,
could you try the following link and say if it works for you? 
https://tubcloud.tu-berlin.de/s/sMj8Nr73a9djFGZ/download/DeepLabV3+_WideResNet38_epoch_4_alpha_0.9.pth

**Comment by 343gltysprk** [comment]
Yes, it works. Thank you, Robin.
