### ISSUE TITLE
Reproducing mIoU

### ISSUE THREAD

**Issue by anohdnu** [robin-chan/meta-ood#7]
Hi Robin,
Thank you for sharing this code. I reproduced the results in your paper except for the mIoU for ID val set. Could you please help how to calculate this ID segmentation metric? 

Thank you

**Comment by robin-chan** [comment]
Hi Nimeshika,
I used the Cityscapes implementation for the mIoU on the Cityscapes val set: https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/evaluation/evalPixelLevelSemanticLabeling.py

**Comment by anohdnu** [comment]
Thank you Robin
